### ISSUE TITLE
load-self-mix.dll编译疑似错误

### ISSUE THREAD

**Issue by 739099308** [luciouskami/load-self-mix#2]
提示我使用win10 SDK10.0.15063.0，然而我的SDK列表里只有10.0.16299.0，编译出的dll不知是否有效，但按照下面附的教程操作后生成的mix文件没有生效，没有被YDWE进程加载。怀疑不同版本的SDK编译时会有问题，特此求教！

**Comment by 739099308** [comment]
https://pan.baidu.com/s/1o8KczMy

whfs

文件太大，只能发百度云，大佬有时间的话就帮个忙吧！

**Comment by 739099308** [comment]
下载到了15063的SDK，编译没报错，但是mix文件仍然无效

**Comment by luciouskami** [comment]
fixed
